dist: bionic
before_install:
  - sudo apt-get -y install libgsl-dev r-cran-glmnet build-essential
  - Rscript -e "install.packages('devtools')"
  - Rscript -e "devtools::install_deps(dependencies=TRUE)"
  - Rscript -e "devtools::document()"
addons:
  apt:
    update: true

# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
env:
  global:
    - _R_CHECK_FORCE_SUGGESTS_=FALSE

language: R
sudo: false
cache: packages
after_success:
  - Rscript -e 'covr::codecov(path = "R/", line_exclusions = list("R/method_plot.R" = c(54, 79), "R/glmdisc.R" = 4:5))'
